/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 42
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_regular_expr = 2,
  anon_sym_POUND = 3,
  sym_number = 4,
  sym_comment = 5,
  anon_sym_node = 6,
  anon_sym_is = 7,
  anon_sym_token = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_abstract = 11,
  anon_sym_optional = 12,
  anon_sym_array = 13,
  anon_sym_LBRACK = 14,
  anon_sym_COMMA = 15,
  anon_sym_RBRACK = 16,
  sym_source_file = 17,
  sym_regex_ref = 18,
  sym__definition = 19,
  sym__node_declaration = 20,
  sym_token_definition = 21,
  sym_node_definition = 22,
  sym_abstract_node_definition = 23,
  sym__field = 24,
  sym_node_field = 25,
  sym__repeat_modifier = 26,
  aux_sym_source_file_repeat1 = 27,
  aux_sym_node_definition_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_regular_expr] = "regular_expr",
  [anon_sym_POUND] = "#",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [anon_sym_node] = "node",
  [anon_sym_is] = "is",
  [anon_sym_token] = "token",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_abstract] = "abstract",
  [anon_sym_optional] = "optional",
  [anon_sym_array] = "array",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [sym_source_file] = "source_file",
  [sym_regex_ref] = "regex_ref",
  [sym__definition] = "_definition",
  [sym__node_declaration] = "_node_declaration",
  [sym_token_definition] = "token_definition",
  [sym_node_definition] = "node_definition",
  [sym_abstract_node_definition] = "abstract_node_definition",
  [sym__field] = "_field",
  [sym_node_field] = "node_field",
  [sym__repeat_modifier] = "_repeat_modifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_node_definition_repeat1] = "node_definition_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_regular_expr] = sym_regular_expr,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [anon_sym_node] = anon_sym_node,
  [anon_sym_is] = anon_sym_is,
  [anon_sym_token] = anon_sym_token,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_abstract] = anon_sym_abstract,
  [anon_sym_optional] = anon_sym_optional,
  [anon_sym_array] = anon_sym_array,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym_regex_ref] = sym_regex_ref,
  [sym__definition] = sym__definition,
  [sym__node_declaration] = sym__node_declaration,
  [sym_token_definition] = sym_token_definition,
  [sym_node_definition] = sym_node_definition,
  [sym_abstract_node_definition] = sym_abstract_node_definition,
  [sym__field] = sym__field,
  [sym_node_field] = sym_node_field,
  [sym__repeat_modifier] = sym__repeat_modifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_node_definition_repeat1] = aux_sym_node_definition_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_regular_expr] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_node] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_is] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_token] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_abstract] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_optional] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_array] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_regex_ref] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__node_declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_token_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_node_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_abstract_node_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__field] = {
    .visible = false,
    .named = true,
  },
  [sym_node_field] = {
    .visible = true,
    .named = true,
  },
  [sym__repeat_modifier] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_node_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 12,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 33,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '#', 43,
        ',', 57,
        '/', 2,
        '[', 56,
        ']', 58,
        'a', 7,
        'i', 23,
        'n', 17,
        'o', 20,
        't', 18,
        '{', 49,
        '|', 42,
        '}', 50,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(43);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == 'a') ADVANCE(38);
      if (lookahead == 'o') ADVANCE(36);
      if (lookahead == '|') ADVANCE(42);
      if (lookahead == '}') ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(45);
      END_STATE();
    case 3:
      if (lookahead == '[') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == 'b') ADVANCE(24);
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(26);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == 'k') ADVANCE(11);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(52);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 20:
      if (lookahead == 'p') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(4);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(5);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(47);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(27);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 28:
      if (lookahead == 'y') ADVANCE(54);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_regular_expr);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_node);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_is);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_token);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_abstract);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_optional);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_optional);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_array);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_array);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_regular_expr] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_node] = ACTIONS(1),
    [anon_sym_is] = ACTIONS(1),
    [anon_sym_token] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_abstract] = ACTIONS(1),
    [anon_sym_optional] = ACTIONS(1),
    [anon_sym_array] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(26),
    [sym__definition] = STATE(6),
    [sym__node_declaration] = STATE(30),
    [sym_token_definition] = STATE(6),
    [sym_node_definition] = STATE(6),
    [sym_abstract_node_definition] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_node] = ACTIONS(7),
    [anon_sym_token] = ACTIONS(9),
    [anon_sym_abstract] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_regular_expr,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    ACTIONS(23), 1,
      anon_sym_optional,
    ACTIONS(25), 1,
      anon_sym_array,
    STATE(8), 1,
      sym_regex_ref,
    STATE(23), 1,
      sym__repeat_modifier,
    STATE(4), 3,
      sym__field,
      sym_node_field,
      aux_sym_node_definition_repeat1,
  [33] = 10,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_regular_expr,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(23), 1,
      anon_sym_optional,
    ACTIONS(25), 1,
      anon_sym_array,
    ACTIONS(27), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      sym_regex_ref,
    STATE(23), 1,
      sym__repeat_modifier,
    STATE(2), 3,
      sym__field,
      sym_node_field,
      aux_sym_node_definition_repeat1,
  [66] = 10,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(34), 1,
      sym_regular_expr,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(40), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    ACTIONS(45), 1,
      anon_sym_optional,
    ACTIONS(48), 1,
      anon_sym_array,
    STATE(8), 1,
      sym_regex_ref,
    STATE(23), 1,
      sym__repeat_modifier,
    STATE(4), 3,
      sym__field,
      sym_node_field,
      aux_sym_node_definition_repeat1,
  [99] = 7,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_node,
    ACTIONS(59), 1,
      anon_sym_token,
    ACTIONS(62), 1,
      anon_sym_abstract,
    STATE(30), 1,
      sym__node_declaration,
    STATE(5), 5,
      sym__definition,
      sym_token_definition,
      sym_node_definition,
      sym_abstract_node_definition,
      aux_sym_source_file_repeat1,
  [125] = 7,
    ACTIONS(7), 1,
      anon_sym_node,
    ACTIONS(9), 1,
      anon_sym_token,
    ACTIONS(11), 1,
      anon_sym_abstract,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(67), 1,
      sym_comment,
    STATE(30), 1,
      sym__node_declaration,
    STATE(5), 5,
      sym__definition,
      sym_token_definition,
      sym_node_definition,
      sym_abstract_node_definition,
      aux_sym_source_file_repeat1,
  [151] = 2,
    ACTIONS(69), 3,
      sym_identifier,
      anon_sym_optional,
      anon_sym_array,
    ACTIONS(71), 4,
      sym_regular_expr,
      anon_sym_POUND,
      sym_comment,
      anon_sym_RBRACE,
  [163] = 2,
    ACTIONS(73), 3,
      sym_identifier,
      anon_sym_optional,
      anon_sym_array,
    ACTIONS(75), 4,
      sym_regular_expr,
      anon_sym_POUND,
      sym_comment,
      anon_sym_RBRACE,
  [175] = 2,
    ACTIONS(77), 3,
      sym_identifier,
      anon_sym_optional,
      anon_sym_array,
    ACTIONS(79), 4,
      sym_regular_expr,
      anon_sym_POUND,
      sym_comment,
      anon_sym_RBRACE,
  [187] = 2,
    ACTIONS(81), 3,
      sym_identifier,
      anon_sym_optional,
      anon_sym_array,
    ACTIONS(83), 4,
      sym_regular_expr,
      anon_sym_POUND,
      sym_comment,
      anon_sym_RBRACE,
  [199] = 1,
    ACTIONS(85), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_node,
      anon_sym_token,
      anon_sym_LBRACE,
      anon_sym_abstract,
  [208] = 2,
    ACTIONS(89), 1,
      anon_sym_is,
    ACTIONS(87), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_node,
      anon_sym_token,
      anon_sym_abstract,
  [219] = 1,
    ACTIONS(91), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_node,
      anon_sym_token,
      anon_sym_abstract,
  [227] = 1,
    ACTIONS(93), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_node,
      anon_sym_token,
      anon_sym_abstract,
  [235] = 1,
    ACTIONS(95), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_node,
      anon_sym_token,
      anon_sym_abstract,
  [243] = 1,
    ACTIONS(97), 5,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_node,
      anon_sym_token,
      anon_sym_abstract,
  [251] = 2,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(101), 1,
      anon_sym_LBRACK,
  [258] = 2,
    ACTIONS(87), 1,
      anon_sym_LBRACE,
    ACTIONS(89), 1,
      anon_sym_is,
  [265] = 2,
    ACTIONS(103), 1,
      sym_number,
    ACTIONS(105), 1,
      anon_sym_COMMA,
  [272] = 2,
    ACTIONS(107), 1,
      anon_sym_node,
    STATE(14), 1,
      sym__node_declaration,
  [279] = 2,
    ACTIONS(109), 1,
      sym_number,
    ACTIONS(111), 1,
      anon_sym_RBRACK,
  [286] = 2,
    ACTIONS(113), 1,
      sym_number,
    ACTIONS(115), 1,
      anon_sym_RBRACK,
  [293] = 1,
    ACTIONS(117), 1,
      sym_identifier,
  [297] = 1,
    ACTIONS(119), 1,
      sym_regular_expr,
  [301] = 1,
    ACTIONS(121), 1,
      sym_identifier,
  [305] = 1,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
  [309] = 1,
    ACTIONS(125), 1,
      anon_sym_is,
  [313] = 1,
    ACTIONS(127), 1,
      sym_identifier,
  [317] = 1,
    ACTIONS(129), 1,
      sym_identifier,
  [321] = 1,
    ACTIONS(131), 1,
      anon_sym_LBRACE,
  [325] = 1,
    ACTIONS(133), 1,
      anon_sym_is,
  [329] = 1,
    ACTIONS(135), 1,
      sym_identifier,
  [333] = 1,
    ACTIONS(137), 1,
      sym_identifier,
  [337] = 1,
    ACTIONS(139), 1,
      anon_sym_COMMA,
  [341] = 1,
    ACTIONS(115), 1,
      anon_sym_RBRACK,
  [345] = 1,
    ACTIONS(141), 1,
      sym_identifier,
  [349] = 1,
    ACTIONS(143), 1,
      anon_sym_RBRACK,
  [353] = 1,
    ACTIONS(145), 1,
      sym_identifier,
  [357] = 1,
    ACTIONS(147), 1,
      sym_identifier,
  [361] = 1,
    ACTIONS(149), 1,
      sym_identifier,
  [365] = 1,
    ACTIONS(151), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 99,
  [SMALL_STATE(6)] = 125,
  [SMALL_STATE(7)] = 151,
  [SMALL_STATE(8)] = 163,
  [SMALL_STATE(9)] = 175,
  [SMALL_STATE(10)] = 187,
  [SMALL_STATE(11)] = 199,
  [SMALL_STATE(12)] = 208,
  [SMALL_STATE(13)] = 219,
  [SMALL_STATE(14)] = 227,
  [SMALL_STATE(15)] = 235,
  [SMALL_STATE(16)] = 243,
  [SMALL_STATE(17)] = 251,
  [SMALL_STATE(18)] = 258,
  [SMALL_STATE(19)] = 265,
  [SMALL_STATE(20)] = 272,
  [SMALL_STATE(21)] = 279,
  [SMALL_STATE(22)] = 286,
  [SMALL_STATE(23)] = 293,
  [SMALL_STATE(24)] = 297,
  [SMALL_STATE(25)] = 301,
  [SMALL_STATE(26)] = 305,
  [SMALL_STATE(27)] = 309,
  [SMALL_STATE(28)] = 313,
  [SMALL_STATE(29)] = 317,
  [SMALL_STATE(30)] = 321,
  [SMALL_STATE(31)] = 325,
  [SMALL_STATE(32)] = 329,
  [SMALL_STATE(33)] = 333,
  [SMALL_STATE(34)] = 337,
  [SMALL_STATE(35)] = 341,
  [SMALL_STATE(36)] = 345,
  [SMALL_STATE(37)] = 349,
  [SMALL_STATE(38)] = 353,
  [SMALL_STATE(39)] = 357,
  [SMALL_STATE(40)] = 361,
  [SMALL_STATE(41)] = 365,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_node_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_node_definition_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_node_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_node_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regex_ref, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regex_ref, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_field, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_field, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_field, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_field, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_field, 4, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_field, 4, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node_declaration, 4, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node_declaration, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_definition, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_abstract_node_definition, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_token_definition, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_definition, 4, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__repeat_modifier, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [123] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__repeat_modifier, 4, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__repeat_modifier, 5, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__repeat_modifier, 6, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ash(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ash",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
