/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 41
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_regular_expr = 2,
  anon_sym_POUND = 3,
  sym_number = 4,
  sym__comment = 5,
  anon_sym_node = 6,
  anon_sym_is = 7,
  anon_sym_token = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_abstract = 11,
  anon_sym_optional = 12,
  anon_sym_array = 13,
  anon_sym_LBRACK = 14,
  anon_sym_COMMA = 15,
  anon_sym_RBRACK = 16,
  sym_source_file = 17,
  sym_regex_ref = 18,
  sym__definition = 19,
  sym__node_declaration = 20,
  sym_token_definition = 21,
  sym_node_definition = 22,
  sym_abstract_node_definition = 23,
  sym__field = 24,
  sym__node_field = 25,
  sym__repeat_modifier = 26,
  aux_sym_source_file_repeat1 = 27,
  aux_sym_node_definition_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_regular_expr] = "regular_expr",
  [anon_sym_POUND] = "#",
  [sym_number] = "number",
  [sym__comment] = "_comment",
  [anon_sym_node] = "node",
  [anon_sym_is] = "is",
  [anon_sym_token] = "token",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_abstract] = "abstract",
  [anon_sym_optional] = "optional",
  [anon_sym_array] = "array",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [sym_source_file] = "source_file",
  [sym_regex_ref] = "regex_ref",
  [sym__definition] = "_definition",
  [sym__node_declaration] = "_node_declaration",
  [sym_token_definition] = "token_definition",
  [sym_node_definition] = "node_definition",
  [sym_abstract_node_definition] = "abstract_node_definition",
  [sym__field] = "_field",
  [sym__node_field] = "_node_field",
  [sym__repeat_modifier] = "_repeat_modifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_node_definition_repeat1] = "node_definition_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_regular_expr] = sym_regular_expr,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_number] = sym_number,
  [sym__comment] = sym__comment,
  [anon_sym_node] = anon_sym_node,
  [anon_sym_is] = anon_sym_is,
  [anon_sym_token] = anon_sym_token,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_abstract] = anon_sym_abstract,
  [anon_sym_optional] = anon_sym_optional,
  [anon_sym_array] = anon_sym_array,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym_regex_ref] = sym_regex_ref,
  [sym__definition] = sym__definition,
  [sym__node_declaration] = sym__node_declaration,
  [sym_token_definition] = sym_token_definition,
  [sym_node_definition] = sym_node_definition,
  [sym_abstract_node_definition] = sym_abstract_node_definition,
  [sym__field] = sym__field,
  [sym__node_field] = sym__node_field,
  [sym__repeat_modifier] = sym__repeat_modifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_node_definition_repeat1] = aux_sym_node_definition_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_regular_expr] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym__comment] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_node] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_is] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_token] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_abstract] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_optional] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_array] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_regex_ref] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__node_declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_token_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_node_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_abstract_node_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__field] = {
    .visible = false,
    .named = true,
  },
  [sym__node_field] = {
    .visible = false,
    .named = true,
  },
  [sym__repeat_modifier] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_node_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 10,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 22,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '#', 43,
        ',', 57,
        '/', 2,
        '[', 56,
        ']', 58,
        'a', 7,
        'i', 23,
        'n', 17,
        'o', 20,
        't', 18,
        '{', 49,
        '|', 42,
        '}', 50,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(43);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == 'a') ADVANCE(38);
      if (lookahead == 'o') ADVANCE(36);
      if (lookahead == '|') ADVANCE(42);
      if (lookahead == '}') ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(45);
      END_STATE();
    case 3:
      if (lookahead == '[') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == 'b') ADVANCE(24);
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(26);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == 'k') ADVANCE(11);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(52);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 20:
      if (lookahead == 'p') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(4);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(5);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(47);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(27);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 28:
      if (lookahead == 'y') ADVANCE(54);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_regular_expr);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_node);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_is);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_token);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_abstract);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_optional);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_optional);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_array);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_array);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_regular_expr] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym__comment] = ACTIONS(1),
    [anon_sym_node] = ACTIONS(1),
    [anon_sym_is] = ACTIONS(1),
    [anon_sym_token] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_abstract] = ACTIONS(1),
    [anon_sym_optional] = ACTIONS(1),
    [anon_sym_array] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(27),
    [sym__definition] = STATE(6),
    [sym__node_declaration] = STATE(39),
    [sym_token_definition] = STATE(6),
    [sym_node_definition] = STATE(6),
    [sym_abstract_node_definition] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__comment] = ACTIONS(5),
    [anon_sym_node] = ACTIONS(7),
    [anon_sym_token] = ACTIONS(9),
    [anon_sym_abstract] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 1,
      anon_sym_optional,
    ACTIONS(23), 1,
      anon_sym_array,
    STATE(23), 1,
      sym__repeat_modifier,
    ACTIONS(15), 2,
      sym_regular_expr,
      sym__comment,
    STATE(3), 4,
      sym_regex_ref,
      sym__field,
      sym__node_field,
      aux_sym_node_definition_repeat1,
  [29] = 8,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_POUND,
    ACTIONS(34), 1,
      anon_sym_RBRACE,
    ACTIONS(36), 1,
      anon_sym_optional,
    ACTIONS(39), 1,
      anon_sym_array,
    STATE(23), 1,
      sym__repeat_modifier,
    ACTIONS(28), 2,
      sym_regular_expr,
      sym__comment,
    STATE(3), 4,
      sym_regex_ref,
      sym__field,
      sym__node_field,
      aux_sym_node_definition_repeat1,
  [58] = 8,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(21), 1,
      anon_sym_optional,
    ACTIONS(23), 1,
      anon_sym_array,
    ACTIONS(44), 1,
      anon_sym_RBRACE,
    STATE(23), 1,
      sym__repeat_modifier,
    ACTIONS(42), 2,
      sym_regular_expr,
      sym__comment,
    STATE(2), 4,
      sym_regex_ref,
      sym__field,
      sym__node_field,
      aux_sym_node_definition_repeat1,
  [87] = 7,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    ACTIONS(48), 1,
      sym__comment,
    ACTIONS(51), 1,
      anon_sym_node,
    ACTIONS(54), 1,
      anon_sym_token,
    ACTIONS(57), 1,
      anon_sym_abstract,
    STATE(39), 1,
      sym__node_declaration,
    STATE(5), 5,
      sym__definition,
      sym_token_definition,
      sym_node_definition,
      sym_abstract_node_definition,
      aux_sym_source_file_repeat1,
  [113] = 7,
    ACTIONS(7), 1,
      anon_sym_node,
    ACTIONS(9), 1,
      anon_sym_token,
    ACTIONS(11), 1,
      anon_sym_abstract,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 1,
      sym__comment,
    STATE(39), 1,
      sym__node_declaration,
    STATE(5), 5,
      sym__definition,
      sym_token_definition,
      sym_node_definition,
      sym_abstract_node_definition,
      aux_sym_source_file_repeat1,
  [139] = 2,
    ACTIONS(64), 3,
      sym_identifier,
      anon_sym_optional,
      anon_sym_array,
    ACTIONS(66), 4,
      sym_regular_expr,
      anon_sym_POUND,
      sym__comment,
      anon_sym_RBRACE,
  [151] = 2,
    ACTIONS(68), 3,
      sym_identifier,
      anon_sym_optional,
      anon_sym_array,
    ACTIONS(70), 4,
      sym_regular_expr,
      anon_sym_POUND,
      sym__comment,
      anon_sym_RBRACE,
  [163] = 2,
    ACTIONS(72), 3,
      sym_identifier,
      anon_sym_optional,
      anon_sym_array,
    ACTIONS(74), 4,
      sym_regular_expr,
      anon_sym_POUND,
      sym__comment,
      anon_sym_RBRACE,
  [175] = 2,
    ACTIONS(78), 1,
      anon_sym_is,
    ACTIONS(76), 5,
      ts_builtin_sym_end,
      sym__comment,
      anon_sym_node,
      anon_sym_token,
      anon_sym_abstract,
  [186] = 1,
    ACTIONS(80), 6,
      ts_builtin_sym_end,
      sym__comment,
      anon_sym_node,
      anon_sym_token,
      anon_sym_LBRACE,
      anon_sym_abstract,
  [195] = 1,
    ACTIONS(82), 5,
      ts_builtin_sym_end,
      sym__comment,
      anon_sym_node,
      anon_sym_token,
      anon_sym_abstract,
  [203] = 1,
    ACTIONS(84), 5,
      ts_builtin_sym_end,
      sym__comment,
      anon_sym_node,
      anon_sym_token,
      anon_sym_abstract,
  [211] = 1,
    ACTIONS(86), 5,
      ts_builtin_sym_end,
      sym__comment,
      anon_sym_node,
      anon_sym_token,
      anon_sym_abstract,
  [219] = 1,
    ACTIONS(88), 5,
      ts_builtin_sym_end,
      sym__comment,
      anon_sym_node,
      anon_sym_token,
      anon_sym_abstract,
  [227] = 2,
    ACTIONS(90), 1,
      sym_identifier,
    ACTIONS(92), 1,
      anon_sym_LBRACK,
  [234] = 2,
    ACTIONS(94), 1,
      anon_sym_node,
    STATE(14), 1,
      sym__node_declaration,
  [241] = 2,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(78), 1,
      anon_sym_is,
  [248] = 2,
    ACTIONS(96), 1,
      sym_number,
    ACTIONS(98), 1,
      anon_sym_COMMA,
  [255] = 2,
    ACTIONS(100), 1,
      sym_number,
    ACTIONS(102), 1,
      anon_sym_RBRACK,
  [262] = 2,
    ACTIONS(104), 1,
      sym_number,
    ACTIONS(106), 1,
      anon_sym_RBRACK,
  [269] = 1,
    ACTIONS(108), 1,
      sym_identifier,
  [273] = 1,
    ACTIONS(110), 1,
      sym_identifier,
  [277] = 1,
    ACTIONS(112), 1,
      sym_identifier,
  [281] = 1,
    ACTIONS(114), 1,
      sym_identifier,
  [285] = 1,
    ACTIONS(116), 1,
      anon_sym_is,
  [289] = 1,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
  [293] = 1,
    ACTIONS(120), 1,
      sym_identifier,
  [297] = 1,
    ACTIONS(122), 1,
      sym_regular_expr,
  [301] = 1,
    ACTIONS(124), 1,
      anon_sym_is,
  [305] = 1,
    ACTIONS(126), 1,
      sym_identifier,
  [309] = 1,
    ACTIONS(128), 1,
      sym_identifier,
  [313] = 1,
    ACTIONS(130), 1,
      anon_sym_COMMA,
  [317] = 1,
    ACTIONS(106), 1,
      anon_sym_RBRACK,
  [321] = 1,
    ACTIONS(132), 1,
      sym_identifier,
  [325] = 1,
    ACTIONS(134), 1,
      anon_sym_RBRACK,
  [329] = 1,
    ACTIONS(136), 1,
      sym_identifier,
  [333] = 1,
    ACTIONS(138), 1,
      sym_identifier,
  [337] = 1,
    ACTIONS(140), 1,
      anon_sym_LBRACE,
  [341] = 1,
    ACTIONS(142), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 29,
  [SMALL_STATE(4)] = 58,
  [SMALL_STATE(5)] = 87,
  [SMALL_STATE(6)] = 113,
  [SMALL_STATE(7)] = 139,
  [SMALL_STATE(8)] = 151,
  [SMALL_STATE(9)] = 163,
  [SMALL_STATE(10)] = 175,
  [SMALL_STATE(11)] = 186,
  [SMALL_STATE(12)] = 195,
  [SMALL_STATE(13)] = 203,
  [SMALL_STATE(14)] = 211,
  [SMALL_STATE(15)] = 219,
  [SMALL_STATE(16)] = 227,
  [SMALL_STATE(17)] = 234,
  [SMALL_STATE(18)] = 241,
  [SMALL_STATE(19)] = 248,
  [SMALL_STATE(20)] = 255,
  [SMALL_STATE(21)] = 262,
  [SMALL_STATE(22)] = 269,
  [SMALL_STATE(23)] = 273,
  [SMALL_STATE(24)] = 277,
  [SMALL_STATE(25)] = 281,
  [SMALL_STATE(26)] = 285,
  [SMALL_STATE(27)] = 289,
  [SMALL_STATE(28)] = 293,
  [SMALL_STATE(29)] = 297,
  [SMALL_STATE(30)] = 301,
  [SMALL_STATE(31)] = 305,
  [SMALL_STATE(32)] = 309,
  [SMALL_STATE(33)] = 313,
  [SMALL_STATE(34)] = 317,
  [SMALL_STATE(35)] = 321,
  [SMALL_STATE(36)] = 325,
  [SMALL_STATE(37)] = 329,
  [SMALL_STATE(38)] = 333,
  [SMALL_STATE(39)] = 337,
  [SMALL_STATE(40)] = 341,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_node_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_node_definition_repeat1, 2, 0, 0),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_node_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_node_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regex_ref, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regex_ref, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__node_field, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node_field, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__node_field, 4, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node_field, 4, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node_declaration, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node_declaration, 4, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_definition, 4, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_definition, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_abstract_node_definition, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_token_definition, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__repeat_modifier, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [118] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__repeat_modifier, 4, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__repeat_modifier, 5, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__repeat_modifier, 6, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ash(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ash",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
